package com.example.mapper;

import com.example.pojo.Tadmin;
import com.example.pojo.TadminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TadminMapper {
    List<Tadmin> selectAllAdmin();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TADMIN
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    int countByExample(TadminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TADMIN
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    int deleteByExample(TadminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TADMIN
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    int deleteByPrimaryKey(Long adminid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TADMIN
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    int insert(Tadmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TADMIN
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    int insertSelective(Tadmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TADMIN
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    List<Tadmin> selectByExample(TadminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TADMIN
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    Tadmin selectByPrimaryKey(Long adminid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TADMIN
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    int updateByExampleSelective(@Param("record") Tadmin record, @Param("example") TadminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TADMIN
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    int updateByExample(@Param("record") Tadmin record, @Param("example") TadminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TADMIN
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    int updateByPrimaryKeySelective(Tadmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TADMIN
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    int updateByPrimaryKey(Tadmin record);
}