package com.example.mapper;


import com.example.pojo.Tbook;
import com.example.pojo.TbookExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbookMapper {
    List<Tbook> selectAllBook();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TBOOK
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    int countByExample(TbookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TBOOK
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    int deleteByExample(TbookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TBOOK
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    int deleteByPrimaryKey(Long booksisbn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TBOOK
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    int insert(Tbook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TBOOK
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    int insertSelective(Tbook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TBOOK
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    List<Tbook> selectByExample(TbookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TBOOK
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    Tbook selectByPrimaryKey(Long booksisbn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TBOOK
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    int updateByExampleSelective(@Param("record") Tbook record, @Param("example") TbookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TBOOK
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    int updateByExample(@Param("record") Tbook record, @Param("example") TbookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TBOOK
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    int updateByPrimaryKeySelective(Tbook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TBOOK
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    int updateByPrimaryKey(Tbook record);
}