package com.example.mapper;

import com.example.pojo.Tuser;
import com.example.pojo.TuserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TuserMapper {
    List<Tuser> selectAllUser();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TUSER
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    int countByExample(TuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TUSER
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    int deleteByExample(TuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TUSER
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    int deleteByPrimaryKey(Long usersid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TUSER
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    int insert(Tuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TUSER
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    int insertSelective(Tuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TUSER
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    List<Tuser> selectByExample(TuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TUSER
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    Tuser selectByPrimaryKey(Long usersid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TUSER
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    int updateByExampleSelective(@Param("record") Tuser record, @Param("example") TuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TUSER
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    int updateByExample(@Param("record") Tuser record, @Param("example") TuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TUSER
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    int updateByPrimaryKeySelective(Tuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TUSER
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    int updateByPrimaryKey(Tuser record);
}