package com.example.mapper;

import com.example.pojo.Userborrow;
import com.example.pojo.UserborrowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserborrowMapper {
    int deleteBorrow(Userborrow record);

    int deleteByPrimaryUserKey(long usersid);

    int deleteByPrimaryBookKey(long booksisbn);

    int updateByPrimaryUserKey(Userborrow record);

    int updateByPrimaryBookKey(Userborrow record);

    List<Userborrow> selectByPrimaryUserKey(long usersid);

    List<Userborrow> selectByPrimaryBookKey(long booksisbn);

    List<Userborrow> selectAllBorrow();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.USERBORROW
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    int countByExample(UserborrowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.USERBORROW
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    int deleteByExample(UserborrowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.USERBORROW
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    int insert(Userborrow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.USERBORROW
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    int insertSelective(Userborrow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.USERBORROW
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    List<Userborrow> selectByExample(UserborrowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.USERBORROW
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    int updateByExampleSelective(@Param("record") Userborrow record, @Param("example") UserborrowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.USERBORROW
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    int updateByExample(@Param("record") Userborrow record, @Param("example") UserborrowExample example);
}