package com.example.pojo;

public class Tbook {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.TBOOK.BOOKSISBN
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    private Long booksisbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.TBOOK.BOOKSNAME
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    private String booksname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.TBOOK.BOOKSAUTHOR
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    private String booksauthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.TBOOK.BOOKSTYPE
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    private String bookstype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.TBOOK.BOOKSPRICE
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    private Long booksprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.TBOOK.BOOKSPUBLISHER
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    private String bookspublisher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.TBOOK.BOOKSSTORE
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    private Long booksstore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.TBOOK.BOOKSTOTAL
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    private Long bookstotal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.TBOOK.BOOKSISBN
     *
     * @return the value of USER_INFO.TBOOK.BOOKSISBN
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    public Long getBooksisbn() {
        return booksisbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.TBOOK.BOOKSISBN
     *
     * @param booksisbn the value for USER_INFO.TBOOK.BOOKSISBN
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    public void setBooksisbn(Long booksisbn) {
        this.booksisbn = booksisbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.TBOOK.BOOKSNAME
     *
     * @return the value of USER_INFO.TBOOK.BOOKSNAME
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    public String getBooksname() {
        return booksname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.TBOOK.BOOKSNAME
     *
     * @param booksname the value for USER_INFO.TBOOK.BOOKSNAME
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    public void setBooksname(String booksname) {
        this.booksname = booksname == null ? null : booksname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.TBOOK.BOOKSAUTHOR
     *
     * @return the value of USER_INFO.TBOOK.BOOKSAUTHOR
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    public String getBooksauthor() {
        return booksauthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.TBOOK.BOOKSAUTHOR
     *
     * @param booksauthor the value for USER_INFO.TBOOK.BOOKSAUTHOR
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    public void setBooksauthor(String booksauthor) {
        this.booksauthor = booksauthor == null ? null : booksauthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.TBOOK.BOOKSTYPE
     *
     * @return the value of USER_INFO.TBOOK.BOOKSTYPE
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    public String getBookstype() {
        return bookstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.TBOOK.BOOKSTYPE
     *
     * @param bookstype the value for USER_INFO.TBOOK.BOOKSTYPE
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    public void setBookstype(String bookstype) {
        this.bookstype = bookstype == null ? null : bookstype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.TBOOK.BOOKSPRICE
     *
     * @return the value of USER_INFO.TBOOK.BOOKSPRICE
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    public Long getBooksprice() {
        return booksprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.TBOOK.BOOKSPRICE
     *
     * @param booksprice the value for USER_INFO.TBOOK.BOOKSPRICE
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    public void setBooksprice(Long booksprice) {
        this.booksprice = booksprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.TBOOK.BOOKSPUBLISHER
     *
     * @return the value of USER_INFO.TBOOK.BOOKSPUBLISHER
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    public String getBookspublisher() {
        return bookspublisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.TBOOK.BOOKSPUBLISHER
     *
     * @param bookspublisher the value for USER_INFO.TBOOK.BOOKSPUBLISHER
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    public void setBookspublisher(String bookspublisher) {
        this.bookspublisher = bookspublisher == null ? null : bookspublisher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.TBOOK.BOOKSSTORE
     *
     * @return the value of USER_INFO.TBOOK.BOOKSSTORE
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    public Long getBooksstore() {
        return booksstore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.TBOOK.BOOKSSTORE
     *
     * @param booksstore the value for USER_INFO.TBOOK.BOOKSSTORE
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    public void setBooksstore(Long booksstore) {
        this.booksstore = booksstore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.TBOOK.BOOKSTOTAL
     *
     * @return the value of USER_INFO.TBOOK.BOOKSTOTAL
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    public Long getBookstotal() {
        return bookstotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.TBOOK.BOOKSTOTAL
     *
     * @param bookstotal the value for USER_INFO.TBOOK.BOOKSTOTAL
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    public void setBookstotal(Long bookstotal) {
        this.bookstotal = bookstotal;
    }
}