package com.example.pojo;

import java.util.ArrayList;
import java.util.List;

public class TuserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table USER_INFO.TUSER
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table USER_INFO.TUSER
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table USER_INFO.TUSER
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TUSER
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    public TuserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TUSER
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TUSER
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TUSER
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TUSER
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TUSER
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TUSER
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TUSER
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TUSER
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TUSER
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO.TUSER
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table USER_INFO.TUSER
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUsersidIsNull() {
            addCriterion("USERSID is null");
            return (Criteria) this;
        }

        public Criteria andUsersidIsNotNull() {
            addCriterion("USERSID is not null");
            return (Criteria) this;
        }

        public Criteria andUsersidEqualTo(Long value) {
            addCriterion("USERSID =", value, "usersid");
            return (Criteria) this;
        }

        public Criteria andUsersidNotEqualTo(Long value) {
            addCriterion("USERSID <>", value, "usersid");
            return (Criteria) this;
        }

        public Criteria andUsersidGreaterThan(Long value) {
            addCriterion("USERSID >", value, "usersid");
            return (Criteria) this;
        }

        public Criteria andUsersidGreaterThanOrEqualTo(Long value) {
            addCriterion("USERSID >=", value, "usersid");
            return (Criteria) this;
        }

        public Criteria andUsersidLessThan(Long value) {
            addCriterion("USERSID <", value, "usersid");
            return (Criteria) this;
        }

        public Criteria andUsersidLessThanOrEqualTo(Long value) {
            addCriterion("USERSID <=", value, "usersid");
            return (Criteria) this;
        }

        public Criteria andUsersidIn(List<Long> values) {
            addCriterion("USERSID in", values, "usersid");
            return (Criteria) this;
        }

        public Criteria andUsersidNotIn(List<Long> values) {
            addCriterion("USERSID not in", values, "usersid");
            return (Criteria) this;
        }

        public Criteria andUsersidBetween(Long value1, Long value2) {
            addCriterion("USERSID between", value1, value2, "usersid");
            return (Criteria) this;
        }

        public Criteria andUsersidNotBetween(Long value1, Long value2) {
            addCriterion("USERSID not between", value1, value2, "usersid");
            return (Criteria) this;
        }

        public Criteria andUsersnameIsNull() {
            addCriterion("USERSNAME is null");
            return (Criteria) this;
        }

        public Criteria andUsersnameIsNotNull() {
            addCriterion("USERSNAME is not null");
            return (Criteria) this;
        }

        public Criteria andUsersnameEqualTo(String value) {
            addCriterion("USERSNAME =", value, "usersname");
            return (Criteria) this;
        }

        public Criteria andUsersnameNotEqualTo(String value) {
            addCriterion("USERSNAME <>", value, "usersname");
            return (Criteria) this;
        }

        public Criteria andUsersnameGreaterThan(String value) {
            addCriterion("USERSNAME >", value, "usersname");
            return (Criteria) this;
        }

        public Criteria andUsersnameGreaterThanOrEqualTo(String value) {
            addCriterion("USERSNAME >=", value, "usersname");
            return (Criteria) this;
        }

        public Criteria andUsersnameLessThan(String value) {
            addCriterion("USERSNAME <", value, "usersname");
            return (Criteria) this;
        }

        public Criteria andUsersnameLessThanOrEqualTo(String value) {
            addCriterion("USERSNAME <=", value, "usersname");
            return (Criteria) this;
        }

        public Criteria andUsersnameLike(String value) {
            addCriterion("USERSNAME like", value, "usersname");
            return (Criteria) this;
        }

        public Criteria andUsersnameNotLike(String value) {
            addCriterion("USERSNAME not like", value, "usersname");
            return (Criteria) this;
        }

        public Criteria andUsersnameIn(List<String> values) {
            addCriterion("USERSNAME in", values, "usersname");
            return (Criteria) this;
        }

        public Criteria andUsersnameNotIn(List<String> values) {
            addCriterion("USERSNAME not in", values, "usersname");
            return (Criteria) this;
        }

        public Criteria andUsersnameBetween(String value1, String value2) {
            addCriterion("USERSNAME between", value1, value2, "usersname");
            return (Criteria) this;
        }

        public Criteria andUsersnameNotBetween(String value1, String value2) {
            addCriterion("USERSNAME not between", value1, value2, "usersname");
            return (Criteria) this;
        }

        public Criteria andUserspwdIsNull() {
            addCriterion("USERSPWD is null");
            return (Criteria) this;
        }

        public Criteria andUserspwdIsNotNull() {
            addCriterion("USERSPWD is not null");
            return (Criteria) this;
        }

        public Criteria andUserspwdEqualTo(String value) {
            addCriterion("USERSPWD =", value, "userspwd");
            return (Criteria) this;
        }

        public Criteria andUserspwdNotEqualTo(String value) {
            addCriterion("USERSPWD <>", value, "userspwd");
            return (Criteria) this;
        }

        public Criteria andUserspwdGreaterThan(String value) {
            addCriterion("USERSPWD >", value, "userspwd");
            return (Criteria) this;
        }

        public Criteria andUserspwdGreaterThanOrEqualTo(String value) {
            addCriterion("USERSPWD >=", value, "userspwd");
            return (Criteria) this;
        }

        public Criteria andUserspwdLessThan(String value) {
            addCriterion("USERSPWD <", value, "userspwd");
            return (Criteria) this;
        }

        public Criteria andUserspwdLessThanOrEqualTo(String value) {
            addCriterion("USERSPWD <=", value, "userspwd");
            return (Criteria) this;
        }

        public Criteria andUserspwdLike(String value) {
            addCriterion("USERSPWD like", value, "userspwd");
            return (Criteria) this;
        }

        public Criteria andUserspwdNotLike(String value) {
            addCriterion("USERSPWD not like", value, "userspwd");
            return (Criteria) this;
        }

        public Criteria andUserspwdIn(List<String> values) {
            addCriterion("USERSPWD in", values, "userspwd");
            return (Criteria) this;
        }

        public Criteria andUserspwdNotIn(List<String> values) {
            addCriterion("USERSPWD not in", values, "userspwd");
            return (Criteria) this;
        }

        public Criteria andUserspwdBetween(String value1, String value2) {
            addCriterion("USERSPWD between", value1, value2, "userspwd");
            return (Criteria) this;
        }

        public Criteria andUserspwdNotBetween(String value1, String value2) {
            addCriterion("USERSPWD not between", value1, value2, "userspwd");
            return (Criteria) this;
        }

        public Criteria andUserstelIsNull() {
            addCriterion("USERSTEL is null");
            return (Criteria) this;
        }

        public Criteria andUserstelIsNotNull() {
            addCriterion("USERSTEL is not null");
            return (Criteria) this;
        }

        public Criteria andUserstelEqualTo(String value) {
            addCriterion("USERSTEL =", value, "userstel");
            return (Criteria) this;
        }

        public Criteria andUserstelNotEqualTo(String value) {
            addCriterion("USERSTEL <>", value, "userstel");
            return (Criteria) this;
        }

        public Criteria andUserstelGreaterThan(String value) {
            addCriterion("USERSTEL >", value, "userstel");
            return (Criteria) this;
        }

        public Criteria andUserstelGreaterThanOrEqualTo(String value) {
            addCriterion("USERSTEL >=", value, "userstel");
            return (Criteria) this;
        }

        public Criteria andUserstelLessThan(String value) {
            addCriterion("USERSTEL <", value, "userstel");
            return (Criteria) this;
        }

        public Criteria andUserstelLessThanOrEqualTo(String value) {
            addCriterion("USERSTEL <=", value, "userstel");
            return (Criteria) this;
        }

        public Criteria andUserstelLike(String value) {
            addCriterion("USERSTEL like", value, "userstel");
            return (Criteria) this;
        }

        public Criteria andUserstelNotLike(String value) {
            addCriterion("USERSTEL not like", value, "userstel");
            return (Criteria) this;
        }

        public Criteria andUserstelIn(List<String> values) {
            addCriterion("USERSTEL in", values, "userstel");
            return (Criteria) this;
        }

        public Criteria andUserstelNotIn(List<String> values) {
            addCriterion("USERSTEL not in", values, "userstel");
            return (Criteria) this;
        }

        public Criteria andUserstelBetween(String value1, String value2) {
            addCriterion("USERSTEL between", value1, value2, "userstel");
            return (Criteria) this;
        }

        public Criteria andUserstelNotBetween(String value1, String value2) {
            addCriterion("USERSTEL not between", value1, value2, "userstel");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table USER_INFO.TUSER
     *
     * @mbggenerated do_not_delete_during_merge Sat Apr 20 17:01:17 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table USER_INFO.TUSER
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}