package com.example.pojo;

public class Tuser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.TUSER.USERSID
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    private Long usersid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.TUSER.USERSNAME
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    private String usersname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.TUSER.USERSPWD
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    private String userspwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.TUSER.USERSTEL
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    private String userstel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.TUSER.USERSID
     *
     * @return the value of USER_INFO.TUSER.USERSID
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    public Long getUsersid() {
        return usersid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.TUSER.USERSID
     *
     * @param usersid the value for USER_INFO.TUSER.USERSID
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    public void setUsersid(Long usersid) {
        this.usersid = usersid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.TUSER.USERSNAME
     *
     * @return the value of USER_INFO.TUSER.USERSNAME
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    public String getUsersname() {
        return usersname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.TUSER.USERSNAME
     *
     * @param usersname the value for USER_INFO.TUSER.USERSNAME
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    public void setUsersname(String usersname) {
        this.usersname = usersname == null ? null : usersname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.TUSER.USERSPWD
     *
     * @return the value of USER_INFO.TUSER.USERSPWD
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    public String getUserspwd() {
        return userspwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.TUSER.USERSPWD
     *
     * @param userspwd the value for USER_INFO.TUSER.USERSPWD
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    public void setUserspwd(String userspwd) {
        this.userspwd = userspwd == null ? null : userspwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.TUSER.USERSTEL
     *
     * @return the value of USER_INFO.TUSER.USERSTEL
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    public String getUserstel() {
        return userstel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.TUSER.USERSTEL
     *
     * @param userstel the value for USER_INFO.TUSER.USERSTEL
     *
     * @mbggenerated Sat Apr 20 17:01:17 CST 2019
     */
    public void setUserstel(String userstel) {
        this.userstel = userstel == null ? null : userstel.trim();
    }
}