package com.example.pojo;

public class Userborrow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.USERBORROW.USERSID
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    private Long usersid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.USERBORROW.BOOKSISBN
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    private Long booksisbn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.USERBORROW.USERSID
     *
     * @return the value of USER_INFO.USERBORROW.USERSID
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    public Long getUsersid() {
        return usersid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.USERBORROW.USERSID
     *
     * @param usersid the value for USER_INFO.USERBORROW.USERSID
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    public void setUsersid(Long usersid) {
        this.usersid = usersid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.USERBORROW.BOOKSISBN
     *
     * @return the value of USER_INFO.USERBORROW.BOOKSISBN
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    public Long getBooksisbn() {
        return booksisbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.USERBORROW.BOOKSISBN
     *
     * @param booksisbn the value for USER_INFO.USERBORROW.BOOKSISBN
     *
     * @mbggenerated Sat Apr 20 17:01:18 CST 2019
     */
    public void setBooksisbn(Long booksisbn) {
        this.booksisbn = booksisbn;
    }
}